apiVersion: v1
kind: Namespace
metadata:
  name: poolini
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poolini-deployment
  namespace: poolini
  labels:
    app.kubernetes.io/name: poolini
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: poolini
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poolini
    spec:
      containers:
        - name: poolini
          image: poolini:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              cpu: "400m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: poolini-service
  namespace: poolini
spec:
  selector:
    app.kubernetes.io/name: poolini
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poolini-ingress
  namespace: poolini
spec:
  rules:
  - host: "poolini.poolc.org"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: poolini-service
            port:
              number: 80
