apiVersion: apps/v1
kind: Deployment
metadata:
  name: poolini-deployment
  namespace: poolc
  labels:
    app.kubernetes.io/name: poolini
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poolini
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poolini
    spec:
      imagePullSecrets:
        - name: poolc-github-packages-secret
      containers:
        - name: poolini
          image: ghcr.io/poolc/poolini:latest
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              cpu: "400m"
              memory: "128Mi"
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: poolc-poolini-secrets
                  key: DISCORD_TOKEN
            - name: POOLC_API_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: poolc-poolini-secrets
                  key: POOLC_API_ADMIN_TOKEN
