poolini:
  discord_token: ${DISCORD_TOKEN}
  debug: ${DEBUG}
  bot_name: "poolc"
  start_characters:
    - "."
    - "!"
    - "/"

poolc:
  api:
    base_url: "https://api.poolc.org"
    admin_token: ${POOLC_API_ADMIN_TOKEN}
